// Copies the Verth Helper's AI instructions (built from the guide in src/helper.js) into the
// worker, so the server alone decides what the AI is told. Run after editing the guide:
//   node tools/sync_ai_guide.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { aiInstructions } from '../src/helper.js';
const p = new URL('../worker/src/index.js', import.meta.url);
const src = readFileSync(p, 'utf8');
const start = '// <ai-guide> (generated by tools/sync_ai_guide.mjs; do not edit by hand)\n', end = '// </ai-guide>';
const i = src.indexOf(start), j = src.indexOf(end);
if (i < 0 || j < 0) throw new Error('markers missing in worker/src/index.js');
const out = src.slice(0, i + start.length) + 'export const AI_GUIDE = ' + JSON.stringify(aiInstructions()) + ';\n' + src.slice(j);
if (out !== src) { writeFileSync(p, out); console.log('updated worker AI guide'); } else console.log('worker AI guide already up to date');
